---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

steps:
  # Run tests
  - name: test
    image: golang:1.26.0
    commands:
      - go test -v -race ./services ./types

  # Build and push Docker image to ECR
  - name: build-and-push
    image: plugins/kaniko-ecr
    pull: always
    settings:
      registry: 795250896452.dkr.ecr.us-east-1.amazonaws.com
      repo: docs/github-copier
      create_repository: true
      tags:
        - latest
        - git-${DRONE_COMMIT_SHA:0:8}
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key
      build_args:
        VERSION: ${DRONE_COMMIT_SHA:0:8}
    when:
      event:
        - push
      branch:
        - main
        - kanopy-deployment

  # Deploy to Kanopy staging
  - name: deploy-staging
    image: public.ecr.aws/kanopy/drone-helm:v3
    settings:
      chart: mongodb/web-app
      add_repos: [mongodb=https://10gen.github.io/helm-charts]
      namespace: docs
      release: github-copier
      values: image.tag=git-${DRONE_COMMIT_SHA:0:8},image.repository=795250896452.dkr.ecr.us-east-1.amazonaws.com/docs/github-copier
      values_files: ["kanopy/staging/values.yaml"]
      api_server: https://api.staging.corp.mongodb.com
      kubernetes_token:
        from_secret: staging_kubernetes_token
    when:
      event:
        - push
      branch:
        - main
        - kanopy-deployment

  # Deploy to Kanopy production
  - name: deploy-production
    image: public.ecr.aws/kanopy/drone-helm:v3
    settings:
      chart: mongodb/web-app
      add_repos: [mongodb=https://10gen.github.io/helm-charts]
      namespace: docs
      release: github-copier
      values: image.tag=git-${DRONE_COMMIT_SHA:0:8},image.repository=795250896452.dkr.ecr.us-east-1.amazonaws.com/docs/github-copier
      values_files: ["kanopy/production/values.yaml"]
      api_server: https://api.prod.corp.mongodb.com
      kubernetes_token:
        from_secret: prod_kubernetes_token
    when:
      event:
        - push
      branch:
        - main

trigger:
  branch:
    - main
    - kanopy-deployment
  event:
    - push
    - tag
